# Site settings
title: Thrive Unleashed
tagline: Stand together, Be transformed, Make a difference... Now
url: "http://unleashed.thriveconference.org" # the base hostname & protocol for your site


# Social
socialimg: /img/social.jpg
facebook:
twitter:
github:
googleplus:
instagram:

# Contact
phone: 
email:

# Build settings
markdown: kramdown
sass:
  sass_dir: scss
  style: :compressed
  
exclude: [.scss, README.md, node_modules, gruntfile.js, package.json]

prose:
  metadata:
    - name: "liveStream"
      field:
        element: checkbox
        label: Live Stream On
        help: Toggle live stream on or off
        value: false