# Site settings
title: Thrive Unleashed
tagline: Executing beautiful ideas in Northern California. We push our clients to exceed their goals. Sometimes, that includes creative strategy, branding, design and product development.
url: "http://unleashed.thriveconferences.com" # the base hostname & protocol for your site

# Social
socialimg:
facebook:
twitter:
github:
googleplus:
instagram:

# Contact
phone: 
email:


# Build settings
markdown: kramdown
sass:
  sass_dir: scss
  style: :compressed
  
exclude: [scss, README.md, node_modules, gruntfile.js, package.json]